### ISSUE TITLE
Unpredictable behavior

### ISSUE THREAD

**Issue by gvcormac** [trec-dd/trec-dd-assessing#19]
There are still anomalies in the browse list behavior:

(a) I can't get a browse list until I have judged some (unspecified) number of documents.  Why?  How many?  

(b) I am still seeing documents at the top of the list that I can't get rid of.  Are you caching the list docs?  My conjecture is that the browser shows you a document, but you go back and refresh, but that document you were shown is still at the top of the list, even though Waterloo did not give it to you.  Are you sure that (i) you send all assessments to Waterloo before fetching the list; (ii) you purge all documents on the list and replace them by the newly fetched list?

**Comment by shawn67** [comment]
a). I recall before you mentioning that your system would prefer a certain number of annotations made before our fetching.(although your just email mentioning it's okay with that now)
b). it's on the top is because new fetched documents having lower score, i believe you'll see new fetched documents at top as well in some other cases. Because now only discard eliminate a document from the document list.
